config/routes.rb
Rails.application.routes.draw do

   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # get "up" => "rails/health#show", as: :rails_health_check

  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts

  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
 
  # get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  # patch "/blog_posts/:id", to: "blog_posts#update"

  # delete "/blog_posts/:id", to: "blog_posts#destroy"
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'blog_posts#home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
 end

 
  get 'published_blog_posts', to: 'blog_posts#index', scope: 'published', as: :published_blog_posts
  get 'scheduled_blog_posts', to: 'blog_posts#index', scope: 'scheduled', as: :scheduled_blog_posts
  get 'draft_blog_posts', to: 'blog_posts#index', scope: 'draft', as: :draft_blog_posts
  get 'home', to: 'blog_posts#home', as: :home


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    has_one_attached :cover_image
    has_rich_text :content
    validates :title, presence: true
    validates :content, presence: true

    # scope :sorted, -> {order(published_at: :desc, updated_at: :desc)}
    scope :sorted, -> { order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc)}
    scope :draft, -> { where(published_at: nil) }
    scope :published, -> { where("published_at <= ?", Time.current) }
    scope :scheduled, -> { where("published_at > ?", Time.current) }

    def draft?
        published_at.nil?
    end
    def published?
        published_at? && published_at <= Time.current
    end
    def scheduled?
        published_at? && published_at > Time.current
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #   :confirmable, :registerable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include Pagy::Backend
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
    include ActionView::RecordIdentifier
    before_action :authenticate_user!
    before_action :set_blog_post

    def destroy
        @blog_post.cover_image.purge_later
        respond_to do |format|
            format.html {redirect_to edit_blog_post_path(@blog_post)}
            format.turbo_stream {render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image))}
        end
    end

    private
    def set_blog_post
        @blog_post = BlogPost.find(params[:blog_post_id])
    end

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
      case params[:scope]
      when 'published'
        @blog_posts = apply_filter(BlogPost.published.sorted)
      when 'scheduled'
        @blog_posts = BlogPost.scheduled.sorted if user_signed_in?
      when 'draft'
        @blog_posts = BlogPost.draft.sorted if user_signed_in?
      else
        @blog_posts = user_signed_in? ? apply_filter(BlogPost.sorted) : apply_filter(BlogPost.published.sorted)
      end
  
      @pagy, @blog_posts = pagy(@blog_posts)
          rescue Pagy::OverflowError
          redirect_to root_path(page: 1)
  end

  def show
      @blog_post = BlogPost.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      redirect_to root_path
  end

  def new
      @blog_post = BlogPost.new
  end
  def create
      @blog_post = BlogPost.new(blog_post_params)
      if @blog_post.save
          redirect_to @blog_post
      else
          render :new, status: :unprocessable_entity
      end
  end

  def edit
      @blog_post = BlogPost.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      redirect_to root_path
  end
  def update
      @blog_post = BlogPost.find(params[:id])
      if @blog_post.update(blog_post_params)
          redirect_to @blog_post
      else
          render :edit, status: :unprocessable_entity
      end
  end

  def destroy
      @blog_post = BlogPost.find(params[:id])
      @blog_post.destroy
      redirect_to root_path
  end

  def home
  end



  private
  def blog_post_params
      params.required(:blog_post).permit(:title, :content, :cover_image, :published_at)
  end

  def set_blog_post
      @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      redirect_to root_path
  end
  def apply_filter(blog_posts)
      case params[:filter]
      when 'last_1_day'
        blog_posts.where('created_at >= ?', 1.day.ago)
      when 'last_month'
        blog_posts.where('created_at >= ?', 1.month.ago)
      when 'last_year'
        blog_posts.where('created_at >= ?', 1.year.ago)
      else
        blog_posts
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
include Pagy::Frontend
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form|%>
 <% if form.object.errors.any? %>
  <div>
    <%form.object.errors.full_messages.each do |message|%>
        <div>
            <%=message%>
        </div>
    <%end%>
  </div>
  <%end%>
    <div>
        <%= form.label :title%>
        <%= form.text_field :title%>
    </div>
    <div>
        <%= form.label :cover_image%>
        <% if blog_post.cover_image.present? %>
          <div id="<%= dom_id(blog_post, :cover_image)%>">
             <%= image_tag blog_post.cover_image, class: "w-1/3"%>
             <%= link_to "Remove cover image", blog_post_cover_image_path(blog_post), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
          </div>
        <%end%>
        <%= form.file_field :cover_image%>
    </div> 
     <div>
        <%= form.label :content %>
        <%= form.rich_text_area :content %>
    </div>
    <div>
        <%= form.label :published_at%>
        <%= form.datetime_select :published_at, include_blank: true%>
    </div>
    <%=form.button%>
<%end%>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render partial: "form", locals: {blog_post: @blog_post}%>
<%= button_to "Delete", @blog_post, method: :delete, data:{turbo_confirm: "Are you sure?"} %>

app/views/blog_posts/home.html.erb
<div class="filter-buttons">
    <h2>Filter Posts:</h2>
    <%= link_to "Last 1 Day", blog_posts_path(filter: 'last_1_day'), class: "filter-button" %>
    <%= link_to "Last Month", blog_posts_path(filter: 'last_month'), class: "filter-button" %>
    <%= link_to "Last Year", blog_posts_path(filter: 'last_year'), class: "filter-button" %>
    <%= link_to "All Posts", blog_posts_path(filter: 'all'), class: "filter-button" %>
  </div>
<div class="full-width-image-container">
    <%= image_tag('welcome', style: 'width: 100%; height: 94.7%; position: absolute; top: 0; left: 0;', alt: 'Description of the image') %>
</div>

app/views/blog_posts/index.html.erb
<h1>My Blog</h1>

<% @blog_posts.each do |blog_post|%>
 <div>
      <%= image_tag blog_post.cover_image if blog_post.cover_image.present?  %>
    <h2><%= link_to blog_post.title, blog_post %></h2>
     <% if blog_post.draft?%>
            <div class="p-2 rounded bg-red-500 text-red-900">Draft</div>
          <% elsif blog_post.scheduled?%>
            <div class="p-2 rounded bg-blue-400 text-blue-900">Scheduled</div>
      <%end%>
         <%= blog_post.content %>
 </div>
<%end%>

 <% if @pagy.count > @pagy.items%>
   <div class="my-16">
    <%== pagy_nav(@pagy) %>
   </div>
<%end%>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render partial: "form", locals: {blog_post: @blog_post}%>

app/views/blog_posts/show.html.erb
<%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>
<%= image_tag @blog_post.cover_image if @blog_post.cover_image.present?  %>
<h1><%= @blog_post.title %></h1>
<%= @blog_post.content %>

app/views/layouts/_navbar.html.erb
<nav  class="navbar navbar-expand-lg navbar-light bg-light fixed-top" style="height: 60px;">
  <div class="container-fluid">
    <div class="navbar-brand">
      Welcome, <%= current_user.email if user_signed_in? %>
    </div>

     <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div>
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="filterDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="position:relative; top: -8px;">
              Filter Posts
            </a>
            <div class="dropdown-menu" aria-labelledby="filterDropdown">
              <%= link_to "Last 1 Day", blog_posts_path(filter: 'last_1_day'), class: "dropdown-item" %>
              <%= link_to "Last Month", blog_posts_path(filter: 'last_month'), class: "dropdown-item" %>
              <%= link_to "Last Year", blog_posts_path(filter: 'last_year'), class: "dropdown-item" %>
              <%= link_to "All Posts", blog_posts_path(filter: 'all'), class: "dropdown-item" %>
            </div>
          </li>
        <% end %>

        
        <%= link_to "Home", authenticated_root_path, class: "nav-link" if user_signed_in? %>
         <%= link_to "All Posts", blog_posts_path, class: "nav-link" if user_signed_in?%>
        <%= link_to "Draft Posts", draft_blog_posts_path, class: "nav-link" if user_signed_in? %>
        <%= link_to "Scheduled Posts", scheduled_blog_posts_path, class: "nav-link" if user_signed_in? %>
        <%= link_to "Published Posts", published_blog_posts_path, class: "nav-link" if user_signed_in? %>
         <%= link_to "New blog Posts", new_blog_post_path, class: "nav-link" if user_signed_in? %>
         <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" if user_signed_in? %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext",  "data-turbo-track": "reload" %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css' %>
  </head>

  <body class="prose mx-auto">
  

   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

   <%= render 'layouts/navbar' %>



    <div>
      <% if user_signed_in?%>
        <%#= link_to "Profile", edit_user_registration_path%>
        <%#= button_to "Logout", destroy_user_session_path, method: :delete%>
      <%else%>
        <%#= button_to "Login", new_user_session_path%>
        <%#= link_to "Sign up", new_user_registration_path%>
      <%end%>
    </div>
    <div>
      <%= yield %>
    </div>


    <%= javascript_include_tag 'application', 'data-turbo-frame': 'head' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js' %>

  </body>
</html>